# Data Formats
Data formats in R can be divided in to two:
 1. Datatypes - `in what type data is stored?`
 2. Datastructures - `in what form(structure) data is stored?`

### Datatypes:

    1. numeric (integer, single & double)
    2. character
    3. logical (True/False)
    3. complex
    4. raw

In [1]:
# numeric
num1 <- 100
sprintf('num1 :: %d', num1)  # a fancy variant of print for formatting
typeof(num1)

[1] "num1 :: 100"

[1] "double"

double precision is the default for numeric in R

In [2]:
# numeric (decimal)
num2 <- 1.05
sprintf('num2 :: %f', num2)
typeof(num2)

[1] "num2 :: 1.050000"

[1] "double"

In [3]:
# character
chr <- 'A'
sprintf('Character :: %s', chr)
typeof(chr)

[1] "Character :: A"

[1] "character"

In [4]:
# String
str <- 'Apple'
sprintf('Character :: %s', str)
typeof(str)

[1] "Character :: Apple"

[1] "character"

Strings are not consider differently they are consider under character only.

In [5]:
# logical
log <- TRUE # Also we can use T for TRUE 
print(log)
typeof(log)

[1] TRUE


[1] "logical"

In [6]:
# Complex
z <- 1 + 2i 
print(z)
typeof(z)

[1] 1+2i


[1] "complex"

In [7]:
# raw
rw <- raw(2)
print(rw)
typeof(rw)

[1] 00 00


[1] "raw"

## Datastructures:
Datastrucure says in which form your data would be saved in memory.

Types are:

1. Vector - `Homogeneous 1 dimenional array`
2. Matrix/Array - Homogenous; `In R 2D array is called matrix`; `And 3 or more dimentional arrays are refered as arrays`
3. Dataframe - `Heterogenous collection of same dimentional vectors`
4. List - `Heterogenous collection of any datatype or datastructure`

In [8]:
# vector (1D)
v1 <- c(1,2,5,7,9) # C stands for concatenation i.e; these values should be considered as one.
print(v1)
is.vector(v1)

[1] 1 2 5 7 9


[1] TRUE

In [9]:
# matrix (2D)
m1 <- matrix(c(1,2,3,4,5,6), nrow=2)
print(m1)
is.matrix(m1)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


[1] TRUE

In [10]:
# This line is similar to range(1,6) in `python`
print(c(1:5))

[1] 1 2 3 4 5


In [11]:
# Arrays (3D)
arr1 <- array(c(1:27), dim=c(3,3,3)) # dim stands for dimension
print(arr1)
is.array(arr1)

, , 1

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

, , 2

     [,1] [,2] [,3]
[1,]   10   13   16
[2,]   11   14   17
[3,]   12   15   18

, , 3

     [,1] [,2] [,3]
[1,]   19   22   25
[2,]   20   23   26
[3,]   21   24   27



[1] TRUE

In [12]:
# DataFrame
v1 <- c(1,2,3)
v2 <- c('A','B','C')
v3 <- c(T, F, T)

dfa <- as.data.frame(cbind(v1, v2, v3))
print(dfa)
is.data.frame(dfa)

  v1 v2    v3
1  1  A  TRUE
2  2  B FALSE
3  3  C  TRUE


[1] TRUE

In [13]:
# list
vA <- c('a','A')
vB <- c('b', 'B')
vNum <- c(1,2,3)

l1 <- list(vA, vB)
print('List 1')
print(l1)

l2 <- list(vNum, l1)
print('List 2')
print((l2))

is.list(l2)

[1] "List 1"
[[1]]
[1] "a" "A"

[[2]]
[1] "b" "B"

[1] "List 2"
[[1]]
[1] 1 2 3

[[2]]
[[2]][[1]]
[1] "a" "A"

[[2]][[2]]
[1] "b" "B"




[1] TRUE

## Coercion
>changing of datatype

In [14]:
coerc1 <- c(1, "A", TRUE) # values to converted(casted) to least restrictive datatype
print(coerc1)
typeof(coerc1) # here character is most general type

[1] "1"    "A"    "TRUE"


[1] "character"

In [15]:
# remeber R's default type for numeric is double precision
numb <- 15
print(typeof(numb))

numb <- as.integer(numb)
print(typeof(numb))

[1] "double"
[1] "integer"


In [16]:
charVec <- c("1", "2", "3")
print(charVec)
print(typeof(charVec))


charVec <- as.integer(charVec)
print(charVec)
print(typeof(charVec))

[1] "1" "2" "3"
[1] "character"
[1] 1 2 3
[1] "integer"


In [17]:
mat <- matrix(c(1:9), nrow=3)
print(mat)
print(is.matrix(mat))

df <- as.data.frame(mat)
print(df)
print(is.data.frame(df))

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
[1] TRUE
  V1 V2 V3
1  1  4  7
2  2  5  8
3  3  6  9
[1] TRUE
